### ISSUE TITLE
Deployment Error when no GIT user.name is set

### ISSUE THREAD

**Issue by dominiek** [bedrockio/bedrock-cli#8]
```
latest: digest: sha256:f3f345aeea2cdf9dceddd0b5e9a8609e0d87995f7333cc812a9fceb983e33270 size: 2416

=> Rolling out staging api-deployment
deployment.apps/api-deployment unchanged
(node:10953) UnhandledPromiseRejectionWarning: Error
    at exec (/Users/dodo/.bedrock/src/util/shell.js:19:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getMetaData (/Users/dodo/.bedrock/src/cloud/rollout.js:23:18)
    at async rolloutDeployment (/Users/dodo/.bedrock/src/cloud/rollout.js:61:20)
    at async deploy (/Users/dodo/.bedrock/src/cloud/index.js:230:5)
    at async Command.<anonymous> (/Users/dodo/.bedrock/bin/bedrock:79:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10953) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10953) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

when `git config user.name` returns nothing

**Comment by andrewplummer** [comment]
quick fix here: https://github.com/bedrockio/bedrock-cli/pull/9

**Comment by andrewplummer** [comment]
fixed
